Gestionary/GestionaryWebsite/Pages/AddProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using GestionaryWebsite.DataAccess.Interfaces;
using Microsoft.AspNetCore.Mvc.Rendering;
using GestionaryWebsite.Dbo;
using System.IO;

namespace GestionaryWebsite
{
    public class AddProductModel : PageModel
    {

        public string userName;

        [BindProperty]
        [Required]
        public string Name { get; set; }

        [BindProperty]
        [Required]
        public long Type { get; set; }

        [BindProperty]
        [Required]
        public decimal Price { get; set; }

        [BindProperty]
        [Required]
        public int Stock { get; set; }

        [BindProperty]
        [Required]
        public string Image { get; set; }

        public const string MessageKey = nameof(MessageKey);

        public List<SelectListItem> TypeOptions { get; set; }
        public List<SelectListItem> Images { get; set; }

        private IStockRepository _stockRepository { get; }
        private IEmployeeRepository _employeeRepository { get; }
        private ILogRepository _logRepository { get; }

        public AddProductModel(IStockRepository stockRepository, IEmployeeRepository employeeRepository, ILogRepository logRepository)
        {
            _stockRepository = stockRepository;
            _employeeRepository = employeeRepository;
            _logRepository = logRepository;
        }

        private void resetTypeDropdownList()
        {
            TypeOptions = _stockRepository.GetTypes().Select(t =>
                                  new SelectListItem
                                  {
                                      Value = t.Id.ToString(),
                                      Text = t.Name
                                  }).ToList();

            Images = Directory.EnumerateFiles("wwwroot/Pics/").Select(item => 
                                  new SelectListItem
                                  {
                                      Value = item.Split("/").Last(),
                                      Text = item.Split("/").Last()
                                  }).ToList();
        }

        public IActionResult OnGet()
        {
            userName =  Tools.checkUser(Request.Cookies["user"], _employeeRepository, 1);
            if(userName == null)
                return RedirectToPage("/Login");

            resetTypeDropdownList();
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            resetTypeDropdownList();

            if (!ModelState.IsValid)
            {
                TempData[MessageKey] = "Le formulaire n'est pas valide.";
                return Page();
            }

            await _stockRepository.Insert(new Dbo.ClientItems()
            {
                Name = Name,
                Price = Price,
                Stock = Stock,
                TypeId = Type,
                PicName = Image
            });

            ClientLogs log = new ClientLogs
            {
                Id = 0,
                Date = DateTime.Now,
                Class = this.GetType().Name,
                Type = "Add",
                Logtype = LoggerType.INFO.GetFriendlyName(),
                Message = "Product: " + Name + " has been added to the Stock base",
            };

            await _logRepository.Insert(log);

            TempData[MessageKey] = "Le produit a bien été enregistré !";
            ModelState.Clear();
            return Page();
        }
    }
}

Gestionary/GestionaryWebsite/Pages/AdminAddEmployee.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using GestionaryWebsite.Dbo;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GestionaryWebsite
{
    public class AdminAddEmployeeModel : PageModel
    {
        public string userName;

        private readonly DataAccess.Interfaces.IEmployeeRepository _employeeRepository;
        private readonly DataAccess.Interfaces.ILogRepository _logRepository;

        [BindProperty(SupportsGet = true)]
        [Required]
        public string newName { get; set; }
        [BindProperty(SupportsGet = true)]
        [Required]
        public string newPassword { get; set; }
        [BindProperty(SupportsGet = true)]
        [Required]
        public string confirmPassword { get; set; }

        [BindProperty(SupportsGet = true)]
        public bool newRole { get; set; }
        public const string MessageKey = nameof(MessageKey);

        public AdminAddEmployeeModel(DataAccess.Interfaces.IEmployeeRepository employeeRepository, DataAccess.Interfaces.ILogRepository logRepository)
        {
            _employeeRepository = employeeRepository;
            _logRepository = logRepository;

        }
        public IActionResult OnGet()
        {
            userName = Tools.checkUser(Request.Cookies["user"], _employeeRepository, 2);
            if (userName == null)
                return RedirectToPage("/Login");
            return Page();
        }

        public async Task<IActionResult>  OnPost()
        {
            if (!ModelState.IsValid)
            {
                TempData[MessageKey] = "Le formulaire n'est pas valide.";
                return Page();
            }
            if (newName != null && newPassword == confirmPassword)
            {
                var roles = _employeeRepository.GetTypeRoles();
                var nbRoleAdmin = roles.Where(item => item.Name.ToLower().Contains("admin")).FirstOrDefault();
                var nbRoleEmployee = roles.Where(item => item.Name.ToLower().Contains("employee")).FirstOrDefault();
                
                //default value
                long role = 1;

                if (nbRoleEmployee != null)
                    role = nbRoleEmployee.Id;

                if (newRole && nbRoleAdmin != null)
                    role = nbRoleAdmin.Id;

                

                newPassword =  Tools.Hash(newPassword);
                Dbo.ClientUsers newUser = new Dbo.ClientUsers
                {
                    Username = newName,
                    PasswordHash = newPassword,
                    RoleId = role
                };
                var test = await _employeeRepository.Insert(newUser);


                ClientLogs log = new ClientLogs
                {
                    Id = 0,
                    Date = DateTime.Now,
                    Class = this.GetType().Name,
                    Type = "Add Employee",
                    Logtype = LoggerType.INFO.GetFriendlyName(),
                    Message = "Employee: " + newName + " bas been added to the base",
                };

                await _logRepository.Insert(log);

                return RedirectToPage("./AdminEmployees");
            }
            return Page();

        }
    }
}

Gestionary/GestionaryWebsite/Pages/AdminEmployees.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using GestionaryWebsite.DataAccess.Interfaces;
using GestionaryWebsite.Dbo;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GestionaryWebsite
{
    public class AdminEmployeesModel : PageModel
    {
        public string userName;

        [BindProperty(SupportsGet = true)]
        [Required]
        public string EmployeeId { get; set; }

        private IEmployeeRepository _employeeRepository { get; }
        private ILogRepository _logRepository { get; }
   

        public AdminEmployeesModel(IEmployeeRepository employeeRepository, ILogRepository logRepository)
        {
            _employeeRepository = employeeRepository;
            _logRepository = logRepository;
        }
        public IActionResult OnGet()
        {
            userName = Tools.checkUser(Request.Cookies["user"], _employeeRepository, 2);
            if (userName == null)
                return RedirectToPage("/Login");
            return Page();
        }

        public IEnumerable<Tuple<ClientUsers, string>> GetAllUser()
        {

            var listClientUsers = _employeeRepository.Get().Result;
            var roles = _employeeRepository.GetRoles();

            List<Tuple<ClientUsers, string>> res = new List<Tuple<ClientUsers, string>>();
            foreach (var item in listClientUsers)
            {
                res.Add(new Tuple<ClientUsers, string>(item, getRoleName(item.RoleId, roles)));
            }
            return res;
        }

        private string getRoleName(long roleId, List<ClientUsersRoles> roles)
        {
            var role = roles.Where(role => role.RoleId == roleId).FirstOrDefault();
            if (role == null)
                return "None";
            return role.RoleName;
        }

        public async Task<IActionResult> OnPost()
        {
            ClientUsers employee = _employeeRepository.Get().Result.Where(emp => emp.Id == Int64.Parse(EmployeeId)).FirstOrDefault();
            await _employeeRepository.Delete(Int64.Parse(EmployeeId));

            ClientLogs log = new ClientLogs {
                Id = 0,
                Date = DateTime.Now,
                Class = this.GetType().Name,
                Type = "Delete",
                Logtype = LoggerType.INFO.GetFriendlyName(),
                Message = "Employee: " + employee == null ? "" : employee.Username + " has been removed from the employee base",
            };

            await _logRepository.Insert(log);

            userName = Tools.checkUser(Request.Cookies["user"], _employeeRepository, 2);
            if (userName == null)
                return RedirectToPage("/Login");

            return Page();
        }
    }
}

Gestionary/GestionaryWebsite/Pages/EmployeeProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using GestionaryWebsite.DataAccess.Interfaces;
using GestionaryWebsite.Dbo;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace GestionaryWebsite
{
    public class EmployeeProfileModel : PageModel
    {

        public  string userName;

        private static string userNAME;
       
        [BindProperty(SupportsGet = true)]
        [Required]
        public string oldPassword { get; set; }

        [BindProperty(SupportsGet = true)]
        [Required]
        public string newPassword { get; set; }
        [BindProperty(SupportsGet = true)]
        [Required]
        public string confirmPassword { get; set; }

        private IEmployeeRepository _employeeRepository { get; }
        private ILogRepository _logRepository { get; }

        public const string MessageKey = nameof(MessageKey);
        public EmployeeProfileModel(IEmployeeRepository employeeRepository, DataAccess.Interfaces.ILogRepository logRepository)
        {
            _employeeRepository = employeeRepository;
            _logRepository = logRepository;
        }
        public IActionResult OnGet()
        {
            if (Request.Cookies["user"] == null)
                return RedirectToPage("/Login");

            long userId = long.Parse(Request.Cookies["user"]);
            var listClientUsers = _employeeRepository.Get().Result;
          
            foreach(var item in listClientUsers)
            {
                if(item.Id == userId)
                {
                    userName = item.Username;
                    userNAME = item.Username;
                    break;
                }
            }
            if(userName == null)
                 return RedirectToPage("/Login");
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                TempData[MessageKey] = "Le formulaire n'est pas valide.";
                return Page();
            }

            var employees = _employeeRepository.Get().Result;
            var employee = employees.Where(emp => emp.Username == userNAME).FirstOrDefault();
            if (Tools.CheckPassword(employee.PasswordHash, oldPassword) == false )
            {
                TempData[MessageKey] = "Votre ancien mot de passe n'est pas correct.";
                return Page();
            }
               

            if (newPassword != confirmPassword)
            {
                TempData[MessageKey] = "Les 2 champs nouveaux mots de passe ne correspondent pas.";
                return Page();
            }
               

            newPassword = Tools.Hash(newPassword);
            Dbo.ClientUsers newUser = new Dbo.ClientUsers
            {
                Id = employee.Id,
                Username = employee.Username,
                PasswordHash = newPassword,
                RoleId = employee.RoleId
            };
            var result = _employeeRepository.Update(newUser);


            ClientLogs log = new ClientLogs
            {
                Id = 0,
                Date = DateTime.Now,
                Class = this.GetType().Name,
                Type = "employee.Username",
                Logtype = LoggerType.INFO.GetFriendlyName(),
                Message = "Employee: " + employee.Username + " bas been update to the base",
            };

            await _logRepository.Insert(log);
            TempData[MessageKey] = "Votre profil a bien été éditer !";
            ModelState.Clear();
            OnGet();

            return Page();
        }

    }
}

Gestionary/GestionaryWebsite/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace GestionaryWebsite.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Gestionary/GestionaryWebsite/Pages/Index.cshtml.cs
using GestionaryWebsite.DataAccess.Interfaces;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GestionaryWebsite.Pages
{
    public class IndexModel : PageModel
    {
        public string userName;
        public string UserNameAdmin;

        private IEmployeeRepository _employeeRepository { get; }


        public IndexModel(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }
        public void OnGet()
        {
            userName = Request.Cookies["userName"];
            UserNameAdmin = Tools.checkUser(Request.Cookies["user"], _employeeRepository, 2);
        }
    }
}

Gestionary/GestionaryWebsite/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace GestionaryWebsite.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Gestionary/GestionaryWebsite/Pages/ProductDetail.cshtml.cs
using GestionaryWebsite.DataAccess.Interfaces;
using GestionaryWebsite.Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;

namespace GestionaryWebsite
{
    public class ProductDetailModel : PageModel
    {
        public string userName;

        public long Id { get; set; }

        public string Name { get; set; }
        public string Type { get; set; }
        public string PicName { get; set; }
        public decimal Price { get; set; }
        public long Stock { get; set; }

        public IStockRepository StockRepository { get; }

        public ProductDetailModel(IStockRepository stockRepository)
        {
            StockRepository = stockRepository;
        }

        public IActionResult OnGet(long id)
        {
            userName = Request.Cookies["userName"];
                

            Id = id;
            Dbo.ClientItems item = StockRepository.Get().Result.FirstOrDefault(it => it.Id == id);
            if (item == null)
            {
                return RedirectToPage("/");
            }
            Name = item.Name;
            Price = item.Price;
            Stock = item.Stock;
            PicName = item.PicName;
            Type = StockRepository.GetTypes().FirstOrDefault(t => t.Id == item.TypeId).Name;
            return Page();
        }

        public IActionResult OnPostDelete()
        {
            long id = long.Parse(Request.Form["Id"]);
            bool res = StockRepository.Delete(id).Result;
            return RedirectToPage("/Stock");
        }

        public IActionResult OnPostEdit()
        {
            long id = long.Parse(Request.Form["Id"]);
            return Redirect("/StockHandlerDetail/" + id);
        }
    }
}

Gestionary/GestionaryWebsite/Pages/AddProduct.cshtml
@page
@model GestionaryWebsite.AddProductModel
@{
    ViewData["Title"] = "Nouveau produit";
    ViewData["UserName"] = @Model.userName;
}

<a asp-page="/Stock">&lt; Retour au stocks</a>

<form method="post">
    <center>
        <h1>@ViewData["Title"]</h1>

        @if (TempData[AddProductModel.MessageKey] is string message)
        {
            <p><b>@message</b></p>
        }

        <div class="margin-input">
            <p class="titles-add">Nom du produit:</p>
            <input class="input-add" asp-for="Name" />
        </div>

        <div class="margin-input">
            <div class="titles-add">Type du produit:</div>
            <select class="input-add" asp-items="Model.TypeOptions" asp-for="Type"></select>
        </div>

        <div class="margin-input">
            <p class="titles-add">Prix en euros:</p>
            <input class="input-add" asp-for="Price" />
        </div>

        <div class="margin-input">
            <p class="titles-add">Stock:</p>
            <input class="input-add" asp-for="Stock" />
        </div>

        <div class="margin-input">
            <p class="titles-add">Image:</p>
            <select class="input-add" asp-items="Model.Images" asp-for="Image"></select>
        </div>

        <button class="btn btn-success margin-input">
            Valider
        </button>
    </center>
</form>

Gestionary/GestionaryWebsite/Pages/AdminAddEmployee.cshtml
@page
@model GestionaryWebsite.AdminAddEmployeeModel
@{
    ViewData["Title"] = "AdminAddEmployee";
    ViewData["UserName"] = @Model.userName;
}

<h5>
    <a asp-page="/AdminEmployees">< Retour</a>
</h5>

<center> <h1>Ajouter un employé</h1></center>

<form method="post">
    <center>

        @if (TempData[AdminAddEmployeeModel.MessageKey] is string message)
        {
            <p><b>@message</b></p>
        }

        <div class="margin-input">
            <p class="titles-add">Nom d'utilisateur:</p>
            <input class="input-add" placeholder="Nom" type="text" asp-for="newName" />
        </div>

        <div class="margin-input">
            <p class="titles-add">Mot de passe:</p>
            <input type="password" class="input-add" placeholder="Mot de passe" asp-for="newPassword" />
        </div>

        <div class="margin-input">
            <p class="titles-add">Confirmation du mot de passe:</p>
            <input type="password" class="input-add" placeholder="Mot de passe" asp-for="confirmPassword" />
        </div>

        <div class="margin-input">
            <input type="checkbox" class="form-check-input" asp-for="newRole">
            <label class="titles-add"> Admin</label>
        </div>

        <input type="submit" class="btn btn-success margin-button-submit" value="Valider">
    </center>
</form>

Gestionary/GestionaryWebsite/Pages/AdminEmployees.cshtml
@page
@model GestionaryWebsite.AdminEmployeesModel
@{
    ViewData["Title"] = "AdminEmployees";
    ViewData["UserName"] = @Model.userName;
}

<h1>Liste des employés</h1>

<div class="container">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Nom de l'utilisateur</th>
                <th>Status</th>
                <th>Action</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.GetAllUser())
            {
                <tr>
                    <td>@item.Item1.Username</td>
                    <td>@item.Item2</td>
                    <td>
                        <form method="post">
                            <input type="submit" class="btn btn-danger" value="Renvoyer" />
                            <input type="hidden" name="EmployeeId" value="@item.Item1.Id" />
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-page="/AdminAddEmployee" class="float-right btn btn-success">Ajouter un nouvel utilisateur</a>
</div>

Gestionary/GestionaryWebsite/Pages/EmployeeProfile.cshtml
@page
@model GestionaryWebsite.EmployeeProfileModel
@{
    ViewData["Title"] = "EmployeeProfile";
    ViewData["UserName"] = @Model.userName;
}
<form method="post">
    <center>
        <h3 class="margin-input">@Model.userName</h3>

        @if (TempData[EmployeeProfileModel.MessageKey] is string message)
        {
            <p><b>@message</b></p>
        }

        <div class="margin-input">
            <p class="titles-add">Mot de passe actuel : </p>
            <input class="input-add" placeholder="Mot de passe actuel" type="password" asp-for="oldPassword" />
        </div>

        <div class="margin-input">
            <p class="titles-add">Nouveau mot de passe : </p>
            <input class="input-add" placeholder="Nouveau mot de passe" type="password" asp-for="newPassword" />
        </div>

        <div class="margin-input">
            <p class="titles-add">Confirmer le nouveau mot de passe : </p>
            <input class="input-add" placeholder="Confirmer le mot de passe" type="password" asp-for="confirmPassword" />
        </div>

        <input type="submit" class="btn btn-success margin-input" value="Changer de mot de passe">
    </center>
</form>

Gestionary/GestionaryWebsite/Pages/Index.cshtml
@page
@model GestionaryWebsite.Pages.IndexModel
@{
    ViewData["Title"] = "Home Page";
    ViewData["UserName"] = @Model.userName;
}

    <div class="text-center">
        <h1 class="display-4">Bienvenue</h1>
        <p>Vous êtes sur la page d'accueil de Gestionary.</p>
        <p>Si vous recherchez un produit particulier, allez sur la page dédiée aux <a asp-page="/Stock">stocks</a>.</p>
        @if (ViewData["UserName"] == null)
        {
            <p>Si vous êtes un employé, veuillez vous connecter à l'aide du formulaire de <a asp-page="/Login">connexion</a>.</p>
        }
        @if (Model.UserNameAdmin != null)
        {
            <p><a asp-page="/AdminEmployees">Page Admin</a>.</p>
        }

    </div>

Gestionary/GestionaryWebsite/Pages/Login.cshtml
@page
@model GestionaryWebsite.LoginModel
@{
    ViewData["Title"] = "Connexion";
}
    <form method="post">
        <center>
            <div class="margin-input">
                <h1>@ViewData["Title"]</h1>
            </div>

            <div class="margin-input">
                <input class="input-add" placeholder="Nom d'utilisateur" type="text" asp-for="login" />
            </div>

            <div class="margin-input">
                <input class="input-add" placeholder="Mot de passe" type="password" asp-for="password" />
            </div>

            <input type="submit" class="btn btn-success margin-button-submit" value="Se connecter" />

        </center>
    </form>

Gestionary/GestionaryWebsite/Pages/ProductDetail.cshtml
@page "{id:long}"
@model GestionaryWebsite.ProductDetailModel
@{
    ViewData["Title"] = "Detail";
    ViewData["UserName"] = @Model.userName;
}

<h5>
    <a asp-page="/Stock">< Retour</a>
</h5>

<div class="row">
    
    <div class="col-sm-6">
        <img src="@Href("~/Pics/" + Model.PicName)" class="img-stock-detail">
    </div>

    <div class="col-sm-6 margin-auto">
        <p>
            <b>NOM : </b>@Model.Name
        </p>

        <p>
            <b>TYPE : </b>@Model.Type
        </p>

        <p>
            <b>PRIX : </b>@Model.Price €
        </p>

        <p>
            <b>STOCK RESTANT : </b> @Model.Stock
        </p>

        @if (ViewData["UserName"] != null)
        {
            <form method="post">
                <input type="hidden" value="@Model.Id" name="Id" />
                <input type="submit" class="btn btn-danger" value="Supprimer cette référence" asp-page-handler="Delete" />
                <input type="submit" class="btn btn-primary" value="Modifier" asp-page-handler="Edit" />
            </form>
        }

    </div>
</div>

Gestionary/GestionaryWebsite/Pages/Stock.cshtml
@page
@model GestionaryWebsite.StockModel
@{
    ViewData["Title"] = "Stock";
    ViewData["UserName"] = @Model.userName;
}

<center><h1>@ViewData["Title"]</h1></center>

<div class="container">

    <form class="form-search-stock">
        <div>
            Filtrer par nom : <input type="text" asp-for="SearchString" class="input-search-filter" />
        </div>
        <div>
            Filtrer par type :
            <select asp-for="TypeFilterInput" asp-items="Model.TypesFilters" onchange="this.form.submit()" class="input-search-filter">
                <option value="">Tout</option>
            </select>
        </div>

        @if (ViewData["UserName"] != null)
        {
            <a asp-page="/AddProduct" class="float-right btn btn-success">Ajouter un produit</a>
        }
    </form>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Type</th>
                <th>Prix</th>
                <th>Quantité</th>
                <th>Image</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.StockItems)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price) €
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Stock)
                    </td>
                    <td>
                        <img src="@Href("~/Pics/" + item.PicName)" class="product-image">
                    </td>
                    <td>
                        <a asp-page="/ProductDetail"
                           asp-route-id="@item.Id"
                           ><img src="Pics/visibility_icon.png" /></a>
                    </td>
                </tr>
            }

        </tbody>
    </table>

</div>

Gestionary/GestionaryWebsite/Pages/StockHandlerDetail.cshtml
@page "{id:long}"
@model GestionaryWebsite.StockHandlerDetailModel
@{
    ViewData["Title"] = "StockHandler";
    ViewData["UserName"] = @Model.userName;
}

<h5>
    <a asp-page="/Stock">< Retour</a>
</h5>

<div class="row">

    <div class="col-sm-6">
        <img src="@Href("~/Pics/" + Model.PicName)" class="img-stock-detail">
    </div>

    <div class="col-sm-6 margin-auto">

        <form method="post" enctype="multipart/form-data">

            <div class="margin-input">
                <b>Nom:</b>
                <input class="input-add input-right" type="text" value="@Model.Name" asp-for="Name" />
            </div>

            <div class="margin-input">
                <b>Type:</b>
                <select class="select-add-product input-right" asp-items="Model.TypeOptions" asp-for="Type"></select>
            </div>

            <div class="margin-input">
                <b>Prix:</b>
                <input class="input-add input-right" asp-for="Price" /> €
            </div>

            <div class="margin-input">
                <b>Nombre de produit en stock:</b>
                <input class="input-add input-right" type="number" value="@Model.Stock" asp-for="Stock" />
            </div>


            <div class="margin-input">
                <b>Changer l'image du produit:</b>
                <select class="select-add-product" name="Image" asp-items="Model.Images" asp-for="PicName"></select>
            </div>

            <input type="hidden" class="input-right" value="@Model.Id" name="Id" />
            <input type="submit" class="btn btn-primary input-right" value="Sauvegarder" />
        </form>

    </div>
</div>